use std::fs;
use std::io::Write;
use std::path::Path;
use winres::WindowsResource;
use anyhow::{Context, Result};
use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};

fn aes_encrypt(data: &str, key: &[u8; 32]) -> Result<Vec<u8>> {
    let cipher = Aes256Gcm::new(key.into());
    let mut nonce_bytes = [0u8; 12];
    nonce_bytes.copy_from_slice(&key[..12]);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, data.as_bytes())
        .map_err(|e| anyhow::anyhow!("Encryption failed: {}", e))?;

    Ok(ciphertext)
}

fn format_bytes_array(bytes: &[u8]) -> String {
    let byte_strs: Vec<String> = bytes.iter().map(|b| format!("{}", b)).collect();
    format!("&[{}]", byte_strs.join(", "))
}

fn main() -> Result<()> {
    let config_path = Path::new("src/config.rs");
    let config_content = fs::read_to_string(config_path).context("Failed to read src/config.rs")?;

    let get_val = |key| {
        config_content
            .lines()
            .find(|line| line.trim().starts_with(&format!("{}:", key)))
            .and_then(|line| line.split(':').nth(1))
            .map(|val| {
                let cleaned = val.split("//").next().unwrap_or(val);
                cleaned.trim().trim_matches(',').trim_matches('"')
            })
            .unwrap_or("")
            .to_string()
    };

    let file_ver_str = get_val("file_version");
    let file_name_str = get_val("file_name");
    let product_name = get_val("product_name");
    let description = get_val("description");
    let company_name = get_val("company_name");

    let token = std::env::var("KURINIUM_TOKEN").unwrap_or_else(|_| {
        config_content
            .lines()
            .find(|line| line.contains("DISCORD_TOKEN"))
            .and_then(|line| {
                line.split('"')
                    .nth(1)
                    .map(|s| s.to_string())
            })
            .unwrap_or_else(|| "PLACEHOLDER_TOKEN".to_string())
    });

    let out_dir = std::env::var("OUT_DIR").context("OUT_DIR not set")?;
    let token_path = Path::new(&out_dir).join("encrypted_token.rs");

    let build_timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    
    let junk_size = 1024 + ((build_timestamp % 3072) as usize); // 1KB to 4KB
    let mut junk_bytes: Vec<u8> = Vec::with_capacity(junk_size);
    let mut seed = build_timestamp as u64;
    for _ in 0..junk_size {
        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        junk_bytes.push(((seed >> 33) & 0xFF) as u8);
    }
    let junk_array = format_bytes_array(&junk_bytes);
    let padding_chars: Vec<char> = (0..64).map(|i| {
        let idx = ((build_timestamp >> (i % 64)) & 0x1F) as u8;
        (b'A' + (idx % 26)) as char
    }).collect();
    let random_padding: String = padding_chars.into_iter().collect();
    
    let mut sig_bytes = [0u8; 32];
    let mut sig_seed = build_timestamp.wrapping_add(0xDEADBEEF) as u64;
    for byte in &mut sig_bytes {
        sig_seed = sig_seed.wrapping_mul(6364136223846793005).wrapping_add(1);
        *byte = ((sig_seed >> 33) & 0xFF) as u8;
    }
    let signature_array = format_bytes_array(&sig_bytes);

    let encrypted_bytes = aes_encrypt(&token, &sig_bytes)?;
    let encrypted_array = format_bytes_array(&encrypted_bytes);
    
    let generated_code = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT
// Token is AES-256-GCM encrypted at compile time with BUILD_SIGNATURE

/// Encrypted Discord token bytes
pub const ENCRYPTED_TOKEN: &[u8] = {};

/// Unique build timestamp (nanoseconds)
pub const BUILD_TIMESTAMP: u128 = {};

/// Random 32-byte build signature (changes every build)
#[used]
pub static BUILD_SIGNATURE: &[u8] = {};

/// Random junk data to change file hash (DO NOT REMOVE)
#[used]
#[link_section = ".rdata"]
pub static JUNK_DATA: &[u8] = {};

/// Random padding string
#[used]
pub static RANDOM_PADDING: &str = "{}";

/// Build entropy seed
pub const BUILD_ENTROPY: u64 = {};
"#,
        encrypted_array,
        build_timestamp,
        signature_array,
        junk_array,
        random_padding,
        build_timestamp as u64,
    );
    
    fs::File::create(&token_path)
        .context("Failed to create encrypted_token.rs")?
        .write_all(generated_code.as_bytes())
        .context("Failed to write encrypted_token.rs")?;

    if cfg!(target_os = "windows") {
        let ver_parts: Vec<u64> = file_ver_str
            .split('.')
            .map(|s| s.parse::<u64>().unwrap_or(0))
            .collect();

        let file_ver_u64 = if ver_parts.len() == 4 {
            (ver_parts[0] << 48) | (ver_parts[1] << 32) | (ver_parts[2] << 16) | ver_parts[3]
        } else {
            0x0001000000000000
        };

        WindowsResource::new()
            .set_icon("assets/kurinium.ico")
            .set_version_info(winres::VersionInfo::FILEVERSION, file_ver_u64)
            .set_version_info(winres::VersionInfo::PRODUCTVERSION, file_ver_u64)
            .set("FileVersion", &file_ver_str)
            .set("ProductVersion", &file_ver_str)
            .set("ProductName", &product_name)
            .set("FileDescription", &description)
            .set("CompanyName", &company_name)
            .set("InternalName", &file_name_str) 
            .set("OriginalFilename", &file_name_str)
            .compile()?;
    }
    
    println!("cargo:rerun-if-changed=src/config.rs");
    println!("cargo:rerun-if-env-changed=KURINIUM_TOKEN");

    Ok(())
}